[package]
name = "kumeyuri-render-svg"
version = "0.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/gongahkia/kumeyuri"
description = "SVG renderer for kumeyuri frames and timelines."

[lib]
path = "src/lib.rs"

[dependencies]
kumeyuri-core = { version = "1.1.0-plugins", path = "../kumeyuri-core" }
