[workspace]
members = [
    "crates/mdbook-kumeyuri",
    "crates/kumeyuri-cli",
    "crates/kumeyuri-core",
    "crates/kumeyuri-render-raster",
    "crates/kumeyuri-render-svg",
    "crates/kumeyuri-render-tui",
    "crates/kumeyuri-render-wasm",
]
resolver = "3"

[profile.release]
lto = "thin"
codegen-units = 1

[profile.dist]
inherits = "release"
lto = "thin"
