C4Dynamic
Person(a, "A", "Actor A")
System(b, "B", "System B")
System(c, "C", "System C")
System(d, "D", "System D")
Rel(a, b, "direct", "HTTPS")
BiRel(b, c, "sync")
Rel_Up(c, a, "up")
Rel_Down(a, c, "down")
Rel_Left(c, b, "left")
Rel_Right(b, c, "right")
Rel_Back(c, a, "back")
RelIndex(1, a, b, "indexed", "HTTP")
BiRelIndex(2, b, a, "bi indexed", "WS")
