if(NOT DEFINED STROK_BINARY_DIR OR NOT DEFINED STROK_INSTALL_PREFIX OR
   NOT DEFINED STROK_CARGO_EXECUTABLE OR NOT DEFINED STROK_CARGO_MANIFEST OR
   NOT DEFINED STROK_CARGO_TARGET_DIR)
  message(FATAL_ERROR "Rust installed-binding test requires all configured paths")
endif()

function(run_checked)
  execute_process(
    COMMAND ${ARGN}
    RESULT_VARIABLE status
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
  )
  if(NOT status EQUAL 0)
    string(JOIN " " command ${ARGN})
    message(FATAL_ERROR "${command} failed with status ${status}\n${stdout}${stderr}")
  endif()
endfunction()

run_checked("${CMAKE_COMMAND}" --install "${STROK_BINARY_DIR}" --prefix "${STROK_INSTALL_PREFIX}")

if(EXISTS "${STROK_INSTALL_PREFIX}/lib")
  set(STROK_RUNTIME_LIBRARY_DIR "${STROK_INSTALL_PREFIX}/lib")
elseif(EXISTS "${STROK_INSTALL_PREFIX}/lib64")
  set(STROK_RUNTIME_LIBRARY_DIR "${STROK_INSTALL_PREFIX}/lib64")
else()
  message(FATAL_ERROR "installed strok C ABI library directory was not found")
endif()

if(APPLE)
  set(STROK_RUNTIME_LIBRARY_PATH "${STROK_RUNTIME_LIBRARY_DIR}")
  if(DEFINED ENV{DYLD_LIBRARY_PATH} AND NOT "$ENV{DYLD_LIBRARY_PATH}" STREQUAL "")
    string(APPEND STROK_RUNTIME_LIBRARY_PATH ":$ENV{DYLD_LIBRARY_PATH}")
  endif()
  set(STROK_RUNTIME_ENVIRONMENT "DYLD_LIBRARY_PATH=${STROK_RUNTIME_LIBRARY_PATH}")
elseif(UNIX)
  set(STROK_RUNTIME_LIBRARY_PATH "${STROK_RUNTIME_LIBRARY_DIR}")
  if(DEFINED ENV{LD_LIBRARY_PATH} AND NOT "$ENV{LD_LIBRARY_PATH}" STREQUAL "")
    string(APPEND STROK_RUNTIME_LIBRARY_PATH ":$ENV{LD_LIBRARY_PATH}")
  endif()
  set(STROK_RUNTIME_ENVIRONMENT "LD_LIBRARY_PATH=${STROK_RUNTIME_LIBRARY_PATH}")
endif()

run_checked(
  "${CMAKE_COMMAND}"
  -E env
  "STROK_PREFIX=${STROK_INSTALL_PREFIX}"
  "CARGO_TARGET_DIR=${STROK_CARGO_TARGET_DIR}"
  ${STROK_RUNTIME_ENVIRONMENT}
  "${STROK_CARGO_EXECUTABLE}"
  test
  --locked
  --manifest-path "${STROK_CARGO_MANIFEST}"
)
