graph TD
A[Rectangle] --> B(Round)
B --> C([Stadium])
C --> D[[Subroutine]]
D --> E[(Cylinder)]
E --> F((Circle))
F --> G>Asymmetric]
G --> H{Rhombus}
H --> I{{Hexagon}}
I --> J[/Parallelogram/]
J --> K[\Parallelogram Alt\]
K --> L[/Trapezoid\]
L --> M[\Trapezoid Alt/]
M --> N(((Double Circle)))
