%%{ init: { 'theme': 'base' } }%%
mindmap
  Root((Roadmap))
    Square[Square]
      ::icon(fa fa-square)
      :::urgent large
    Rounded(Rounded)
      Markdown["`**Bold** text`"]
    Circle((Circle))
    Bang))Bang((
    Cloud)Cloud(
    Hex{{Hexagon}}
    Default
