local Biomes = {}

Biomes.order = {
  "cryo_vault",
  "fungal_service",
  "pressure_lab",
  "reactor_trench",
  "waste_artery",
  "storm_drain",
  "ash_foundry",
  "signal_catacombs",
  "bone_market",
  "organ_machine",
}

Biomes.profiles = {
  cryo_vault = {
    label = "CRYO VAULT",
    terrain = "ice",
    district = "cryo_vault",
    signal = "frost_trace",
    hazard = "pit",
    primaryFaction = "predator",
    factions = { "predator", "salvage_clan" },
    incidents = { "blackout", "lockdown", "nest_wake" },
    salvageTools = { "flare", "probe", "oil", "snare", "noisemaker" },
    risk = "fog and brittle seals",
  },
  fungal_service = {
    label = "FUNGAL SERVICE",
    terrain = "fungus",
    district = "fungal_service",
    signal = "spore_bloom",
    hazard = "wire",
    primaryFaction = "salvage_clan",
    factions = { "salvage_clan", "burrow_colony" },
    incidents = { "nest_wake", "vent_bloom", "flood_surge" },
    salvageTools = { "pheromone", "scent", "probe", "snare", "beacon" },
    risk = "false trails and spore scent",
  },
  pressure_lab = {
    label = "PRESSURE LAB",
    terrain = "pressure",
    district = "pressure_lab",
    signal = "pressure_tick",
    hazard = "wire",
    primaryFaction = "machine_nest",
    factions = { "machine_nest", "predator" },
    incidents = { "lockdown", "blackout", "nest_wake" },
    salvageTools = { "probe", "snare", "noisemaker", "flare", "oil" },
    risk = "doors, alarms, and glass sight lines",
  },
  reactor_trench = {
    label = "REACTOR TRENCH",
    terrain = "reactor",
    district = "reactor_trench",
    signal = "radiant_heat",
    hazard = "ember",
    primaryFaction = "screeching_flock",
    factions = { "screeching_flock", "predator" },
    incidents = { "heat_spike", "vent_bloom", "blackout" },
    salvageTools = { "noisemaker", "flare", "probe", "oil", "beacon" },
    risk = "heat, overcharge, and sound panic",
  },
  waste_artery = {
    label = "WASTE ARTERY",
    terrain = "sludge",
    district = "waste_artery",
    signal = "tainted_sludge",
    hazard = "wire",
    primaryFaction = "burrow_colony",
    factions = { "burrow_colony", "salvage_clan" },
    incidents = { "flood_surge", "nest_wake", "lockdown" },
    salvageTools = { "scent", "snare", "pheromone", "oil", "probe" },
    risk = "sludge currents and contaminated salvage",
  },
  storm_drain = {
    label = "STORM DRAIN",
    terrain = "storm",
    district = "storm_drain",
    signal = "surge_line",
    hazard = "wire",
    primaryFaction = "burrow_colony",
    factions = { "burrow_colony", "machine_nest" },
    incidents = { "flood_surge", "lockdown", "vent_bloom" },
    salvageTools = { "probe", "snare", "noisemaker", "oil", "pheromone" },
    risk = "moving flood fronts and live conduits",
  },
  ash_foundry = {
    label = "ASH FOUNDRY",
    terrain = "ash",
    district = "ash_foundry",
    signal = "smoke_veil",
    hazard = "ember",
    primaryFaction = "screeching_flock",
    factions = { "screeching_flock", "salvage_clan" },
    incidents = { "heat_spike", "vent_bloom", "blackout" },
    salvageTools = { "flare", "noisemaker", "probe", "oil", "beacon" },
    risk = "ash curtains, slag lanes, and hot shelter races",
  },
  signal_catacombs = {
    label = "SIGNAL CATACOMBS",
    terrain = "signal",
    district = "signal_catacombs",
    signal = "false_ping",
    hazard = "wire",
    primaryFaction = "machine_nest",
    factions = { "machine_nest", "predator" },
    incidents = { "blackout", "vent_bloom", "nest_wake" },
    salvageTools = { "probe", "beacon", "scent", "snare", "flare" },
    risk = "spoofed map pings and mimic salvage",
  },
  bone_market = {
    label = "BONE MARKET",
    terrain = "bone",
    district = "bone_market",
    signal = "trade_mark",
    hazard = "pit",
    primaryFaction = "salvage_clan",
    factions = { "salvage_clan", "predator" },
    incidents = { "nest_wake", "lockdown", "faction_raid" },
    salvageTools = { "beacon", "scent", "snare", "probe", "oil" },
    risk = "raiders, false trails, and stolen caches",
  },
  organ_machine = {
    label = "ORGAN MACHINE",
    terrain = "organ",
    district = "organ_machine",
    signal = "pulse_mark",
    hazard = "wire",
    primaryFaction = "machine_nest",
    factions = { "machine_nest", "burrow_colony" },
    incidents = { "lockdown", "flood_surge", "heat_spike" },
    salvageTools = { "pheromone", "probe", "snare", "flare", "oil" },
    risk = "living doors, biological alarms, and pulse locks",
  },
}

Biomes.themes = {
  cryo_vault = { "observatory", "archive", "chamber" },
  fungal_service = { "overgrown court", "annex", "cistern" },
  pressure_lab = { "observatory", "machine shaft", "archive" },
  reactor_trench = { "lower foundry", "bridgeworks", "machine shaft" },
  waste_artery = { "cistern", "quarry", "annex" },
  storm_drain = { "cistern", "bridgeworks", "machine shaft" },
  ash_foundry = { "lower foundry", "quarry", "bridgeworks" },
  signal_catacombs = { "observatory", "archive", "machine shaft" },
  bone_market = { "annex", "archive", "quarry" },
  organ_machine = { "machine shaft", "overgrown court", "cistern" },
}

Biomes.roomModifiers = {
  overrun = { signal = "alarm_mark", terrain = "rubble", hazard = "pit", light = 0.42, factionAlarm = 2 },
  starved = { signal = "scratch", terrain = "dust", hazard = nil, light = 0.36, hunger = 0.25 },
  powered = { signal = "pressure_tick", terrain = "glass", hazard = "wire", light = 0.82, powerHint = true },
  flooded = { signal = "wet_tracks", terrain = "water", hazard = "wire", light = 0.46, flood = true },
  hot = { signal = "ash_drift", terrain = "slag", hazard = "ember", light = 0.78, heat = true },
  contested = { signal = "trade_mark", terrain = "bone", hazard = "pit", light = 0.58, factionAlarm = 4 },
  dormant = { signal = "pulse_mark", terrain = "organ", hazard = nil, light = 0.48, shelter = true },
  infested = { signal = "nest_debris", terrain = "fungus", hazard = "wire", light = 0.52, nest = true },
  tarred = { signal = "tainted_sludge", terrain = "tar", hazard = nil, light = 0.34, hunger = 0.18 },
  thorned = { signal = "scratch", terrain = "thorn", hazard = "pit", light = 0.44, factionAlarm = 1 },
  mirrored = { signal = "false_ping", terrain = "mirror", hazard = nil, light = 0.86, powerHint = true },
}

Biomes.modifierOrder = { "overrun", "starved", "powered", "flooded", "hot", "contested", "dormant", "infested", "tarred", "thorned", "mirrored" }

return Biomes
