apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wat.fullname" . }}-postgres
  labels:
    {{- include "wat.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
  database-url: {{ printf "postgres://%s:%s@%s-postgres:5432/%s" .Values.postgres.user .Values.postgres.password (include "wat.fullname" .) .Values.postgres.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wat.fullname" . }}-slack
  labels:
    {{- include "wat.labels" . | nindent 4 }}
type: Opaque
data:
  app-token: {{ .Values.slack.appToken | b64enc | quote }}
  bot-token: {{ .Values.slack.botToken | b64enc | quote }}
  signing-secret: {{ .Values.slack.signingSecret | b64enc | quote }}
  client-id: {{ .Values.slack.clientId | b64enc | quote }}
  client-secret: {{ .Values.slack.clientSecret | b64enc | quote }}
  state-secret: {{ .Values.slack.stateSecret | b64enc | quote }}
  token-encryption-key: {{ .Values.slack.tokenEncryptionKey | b64enc | quote }}
  metrics-token: {{ .Values.slack.metricsToken | b64enc | quote }}
  wat-api-key: {{ .Values.slack.watApiKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wat.fullname" . }}-discord
  labels:
    {{- include "wat.labels" . | nindent 4 }}
type: Opaque
data:
  public-key: {{ .Values.discord.publicKey | b64enc | quote }}
  application-id: {{ .Values.discord.applicationId | b64enc | quote }}
  bot-token: {{ .Values.discord.botToken | b64enc | quote }}
  metrics-token: {{ .Values.discord.metricsToken | b64enc | quote }}
  wat-api-key: {{ .Values.discord.watApiKey | b64enc | quote }}
