apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wat.fullname" . }}-postgres
  labels:
    {{- include "wat.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
  database-url: {{ printf "postgres://%s:%s@%s-postgres:5432/%s" .Values.postgres.user .Values.postgres.password (include "wat.fullname" .) .Values.postgres.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wat.fullname" . }}-slack
  labels:
    {{- include "wat.labels" . | nindent 4 }}
type: Opaque
data:
  app-token: {{ .Values.slack.appToken | b64enc | quote }}
