%%{ init: { "journey": { "actorColours": ["#224466", "#aa5500"], "sectionFills": ["#f8f8f8"] }, "theme": "base" } }%%
journey
  title Configured Journey
  section Support
    Open ticket: 2: User
    Resolve ticket: 5: Agent, User
