%% comment
%%{ animate: { "mode": "none" } }%%
quadrantChart
x-axis Low Cost --> High Cost
y-axis Low Value --> High Value
quadrant-1 Watch
quadrant-2 Invest
quadrant-3 Drop
quadrant-4 Automate
API: [0.25, 0.75]
Batch: [0.65, 0.35]
classDef focus fill:#f96,stroke:#333
class API focus
