#!/usr/bin/env bash
# regenerate assets/tapes/<preset>.tape for every preset. idempotent.
set -euo pipefail
cd "$(dirname "$0")/.."

PRESETS=(
	minimal claude-inspired opencode-inspired codex-inspired gemini-inspired
	aider-inspired copilot-inspired cursor-inspired amp-inspired
	dracula tokyo-night catppuccin-mocha catppuccin-latte
	nord gruvbox-dark gruvbox-light
)

mkdir -p assets/tapes

for preset in "${PRESETS[@]}"; do
	out="assets/tapes/${preset}.tape"
	cat > "$out" <<EOF
# regenerated by scripts/gen-tapes.sh — edit the script, not this file.
Output assets/preview-${preset}.gif
Set FontSize 14
Set Width 1200
Set Height 740
Set Padding 20
Set Theme "Dracula"
Type "pi -e ." Enter
Sleep 1500ms
Type "/pie preset ${preset}" Enter
Sleep 1500ms
Type "list the typescript files in this repo" Enter
Sleep 6s
Type "/quit" Enter
EOF
done

echo "wrote ${#PRESETS[@]} tapes to assets/tapes/"
