#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/docs/comparison/static-parity.md"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

FIXTURES=(
  single_node
  single_node_longer_name
  two_nodes_linked
  two_nodes_longer_names
  three_nodes
  three_nodes_single_line
  two_layer_single_graph
  graph_tb_direction
  flowchart_tb_simple
  comments
  back_reference_from_child
  preserve_order_of_definition
)

extract_source() {
  awk '/^---$/ { exit } { print }' "$1"
}

extract_output() {
  awk 'seen { print } /^---$/ { seen = 1; next }' "$1"
}

html_escape() {
  sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

{
  printf '# Static Parity Comparison\n\n'
  printf '<!-- generated by scripts/generate-static-comparison.sh; do not edit by hand -->\n\n'
  printf 'This page renders the same Mermaid input through Kumeyuri and compares it with vendored reference outputs from `beautiful-mermaid` and `mermaid-ascii`.\n\n'
} > "$OUT"

for fixture in "${FIXTURES[@]}"; do
  beautiful="$ROOT/tests/golden/beautiful-mermaid/testdata/ascii/$fixture.txt"
  mermaid_ascii="$ROOT/tests/golden/mermaid-ascii/testdata/ascii/$fixture.txt"
  source="$TMPDIR/$fixture.mmd"
  beautiful_source="$TMPDIR/$fixture.beautiful.mmd"
  kumeyuri_output="$TMPDIR/$fixture.kumeyuri.txt"
  beautiful_output="$TMPDIR/$fixture.beautiful.txt"
  mermaid_ascii_output="$TMPDIR/$fixture.mermaid-ascii.txt"

  extract_source "$mermaid_ascii" > "$source"
  extract_source "$beautiful" > "$beautiful_source"
  if ! cmp -s "$source" "$beautiful_source"; then
    printf 'source mismatch for %s\n' "$fixture" >&2
    exit 1
  fi

  cargo run -q -p kumeyuri-cli -- render "$source" --format text > "$kumeyuri_output"
  extract_output "$beautiful" > "$beautiful_output"
  extract_output "$mermaid_ascii" > "$mermaid_ascii_output"

  {
    printf '## `%s`\n\n' "$fixture"
    printf '```mermaid\n'
    cat "$source"
    printf '```\n\n'
    printf '<table>\n<thead><tr><th>Kumeyuri</th><th>beautiful-mermaid</th><th>mermaid-ascii</th></tr></thead>\n<tbody><tr>\n'
    printf '<td><pre><code>'
    html_escape < "$kumeyuri_output"
    printf '</code></pre></td>\n'
    printf '<td><pre><code>'
    html_escape < "$beautiful_output"
    printf '</code></pre></td>\n'
    printf '<td><pre><code>'
    html_escape < "$mermaid_ascii_output"
    printf '</code></pre></td>\n'
    printf '</tr></tbody>\n</table>\n\n'
  } >> "$OUT"
done

printf 'wrote %s\n' "$OUT"
