#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/docs/comparison/static-parity.md"
SITE_OUT="$ROOT/site/vs/index.html"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

FIXTURES=(
  single_node
  single_node_longer_name
  two_nodes_linked
  two_nodes_longer_names
  three_nodes
  three_nodes_single_line
  two_layer_single_graph
  graph_tb_direction
  flowchart_tb_simple
  comments
  back_reference_from_child
  preserve_order_of_definition
)

extract_source() {
  awk '/^---$/ { exit } { print }' "$1"
}

extract_output() {
  awk 'seen { print } /^---$/ { seen = 1; next }' "$1"
}

html_escape() {
  sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

html_status() {
  if cmp -s "$1" "$2"; then
    printf '<span class="status-pass">match</span>'
  else
    printf '<span class="status-warn">diff</span>'
  fi
}

mkdir -p "$(dirname "$SITE_OUT")"

{
  printf '# Static Parity Comparison\n\n'
  printf '<!-- generated by scripts/generate-static-comparison.sh; do not edit by hand -->\n\n'
  printf 'This page renders the same Mermaid input through Kumeyuri and compares it with vendored reference outputs from `beautiful-mermaid` and `mermaid-ascii`.\n\n'
} > "$OUT"

{
  printf '<!doctype html>\n'
  printf '<html lang="en">\n'
  printf '  <head>\n'
  printf '    <meta charset="utf-8">\n'
  printf '    <meta name="viewport" content="width=device-width, initial-scale=1">\n'
  printf '    <title>kumeyuri vs Mermaid ASCII renderers</title>\n'
  printf '    <meta name="description" content="Static parity comparison for kumeyuri, beautiful-mermaid, and mermaid-ascii.">\n'
  printf '    <link rel="stylesheet" href="../styles.css">\n'
  printf '  </head>\n'
  printf '  <body>\n'
  printf '    <header class="site-header">\n'
  printf '      <a class="brand" href="../index.html" aria-label="kumeyuri home">kumeyuri</a>\n'
  printf '      <nav aria-label="Primary">\n'
  printf '        <a href="../index.html#formats">Formats</a>\n'
  printf '        <a href="../index.html#embed">Embed</a>\n'
  printf '        <a href="../index.html#playground">Playground</a>\n'
  printf '        <a href="./">Compare</a>\n'
  printf '        <a href="../blog/launch.html">Blog</a>\n'
  printf '        <a href="https://github.com/gongahkia/kumeyuri">GitHub</a>\n'
  printf '      </nav>\n'
  printf '    </header>\n'
  printf '    <main class="compare-page">\n'
  printf '      <section class="compare-hero" aria-labelledby="compare-title">\n'
  printf '        <p class="section-kicker">Static parity</p>\n'
  printf '        <h1 id="compare-title">kumeyuri vs beautiful-mermaid vs mermaid-ascii</h1>\n'
  printf '        <p class="lede">Every row below uses the same vendored Mermaid input and shows text output from kumeyuri beside reference outputs from beautiful-mermaid and mermaid-ascii.</p>\n'
  printf '        <dl class="compare-stats">\n'
  printf '          <div><dt>Fixture set</dt><dd>%s flowchart cases</dd></div>\n' "${#FIXTURES[@]}"
  printf '          <div><dt>Source</dt><dd>tests/golden</dd></div>\n'
  printf '          <div><dt>Generated by</dt><dd>scripts/generate-static-comparison.sh</dd></div>\n'
  printf '        </dl>\n'
  printf '      </section>\n'
} > "$SITE_OUT"

for fixture in "${FIXTURES[@]}"; do
  beautiful="$ROOT/tests/golden/beautiful-mermaid/testdata/ascii/$fixture.txt"
  mermaid_ascii="$ROOT/tests/golden/mermaid-ascii/testdata/ascii/$fixture.txt"
  source="$TMPDIR/$fixture.mmd"
  beautiful_source="$TMPDIR/$fixture.beautiful.mmd"
  kumeyuri_output="$TMPDIR/$fixture.kumeyuri.txt"
  beautiful_output="$TMPDIR/$fixture.beautiful.txt"
  mermaid_ascii_output="$TMPDIR/$fixture.mermaid-ascii.txt"

  extract_source "$mermaid_ascii" > "$source"
  extract_source "$beautiful" > "$beautiful_source"
  if ! cmp -s "$source" "$beautiful_source"; then
    printf 'source mismatch for %s\n' "$fixture" >&2
    exit 1
  fi

  cargo run -q -p kumeyuri-cli -- render "$source" --format text > "$kumeyuri_output"
  extract_output "$beautiful" > "$beautiful_output"
  extract_output "$mermaid_ascii" > "$mermaid_ascii_output"

  {
    printf '## `%s`\n\n' "$fixture"
    printf '```mermaid\n'
    cat "$source"
    printf '```\n\n'
    printf '<table>\n<thead><tr><th>Kumeyuri</th><th>beautiful-mermaid</th><th>mermaid-ascii</th></tr></thead>\n<tbody><tr>\n'
    printf '<td><pre><code>'
    html_escape < "$kumeyuri_output"
    printf '</code></pre></td>\n'
    printf '<td><pre><code>'
    html_escape < "$beautiful_output"
    printf '</code></pre></td>\n'
    printf '<td><pre><code>'
    html_escape < "$mermaid_ascii_output"
    printf '</code></pre></td>\n'
    printf '</tr></tbody>\n</table>\n\n'
  } >> "$OUT"

  {
    printf '      <section class="compare-fixture" aria-labelledby="fixture-%s">\n' "$fixture"
    printf '        <div class="compare-fixture-header">\n'
    printf '          <h2 id="fixture-%s">%s</h2>\n' "$fixture" "$fixture"
    printf '          <p>Kumeyuri vs beautiful-mermaid: '
    html_status "$kumeyuri_output" "$beautiful_output"
    printf ' · Kumeyuri vs mermaid-ascii: '
    html_status "$kumeyuri_output" "$mermaid_ascii_output"
    printf '</p>\n'
    printf '        </div>\n'
    printf '        <details>\n'
    printf '          <summary>Mermaid input</summary>\n'
    printf '          <pre><code>'
    html_escape < "$source"
    printf '</code></pre>\n'
    printf '        </details>\n'
    printf '        <div class="compare-grid">\n'
    printf '          <article><h3>kumeyuri</h3><pre><code>'
    html_escape < "$kumeyuri_output"
    printf '</code></pre></article>\n'
    printf '          <article><h3>beautiful-mermaid</h3><pre><code>'
    html_escape < "$beautiful_output"
    printf '</code></pre></article>\n'
    printf '          <article><h3>mermaid-ascii</h3><pre><code>'
    html_escape < "$mermaid_ascii_output"
    printf '</code></pre></article>\n'
    printf '        </div>\n'
    printf '      </section>\n'
  } >> "$SITE_OUT"
done

{
  printf '    </main>\n'
  printf '  </body>\n'
  printf '</html>\n'
} >> "$SITE_OUT"

printf 'wrote %s\n' "$OUT"
printf 'wrote %s\n' "$SITE_OUT"
