%%{ init: { "gitGraph": { "showBranches": true, "mainBranchOrder": 0, "rotateCommitLabel": false }, "theme": "base" } }%%
gitGraph BT:
  commit id: "root"
  branch release order: 2
  commit id: "rel"
  switch main
  merge release id: "merge" tag: "v1" type: HIGHLIGHT
