%%{ init: { "timeline": { "disableMulticolor": true }, "theme": "base", "themeVariables": { "cScale0": "#224466" } } }%%
timeline
  title Configured Releases
  section Planning
  section Alpha
    2024 Q1 : Design : Prototype
            : Validate
    2024 Q2 with long label : Launch release candidate : Publish notes
  section Beta
    2024 Q3 : Harden : Expand
